### ISSUE TITLE
Not working for frontend

### ISSUE THREAD

**Issue by yogeshkhasturi** [pavelleonidov/magento2-tinymce4#1]
Hello!

This extension doesn't update editor in the frontend. used this code for calling editor on the frontend in 2.2.7

https://magento.stackexchange.com/questions/232577/magento-2-how-to-add-wysiwyg-editor-in-frontend-phtml-file?rq=1

Please help

Thnkas

**Comment by pavelleonidov** [comment]
Hi Yogesh,

thank you very much for reporting this issue. I have just updated this module to get TinyMCE 4 working on frontend side, so please check out the newest dev-master branch.

Best regards,

Pavel
