### ISSUE TITLE
PHP requirement incompatible

### ISSUE THREAD

**Issue by websiteni** [pavelleonidov/magento2-tinymce4#13]
I'm trying to install the latest version via composer, but I keep getting the following error:

[InvalidArgumentException]
Package pavelleonidov/module-tinymce4 at version  has a PHP requirement incompatible with your PHP version (7.3.16)

**Comment by pavelleonidov** [comment]
Fixed with https://github.com/pavelleonidov/magento2-tinymce4/pull/16
