### ISSUE TITLE
your PHP version (7.3.15) does not satisfy that requirement.

### ISSUE THREAD

**Issue by grega74** [pavelleonidov/magento2-tinymce4#14]
I get following error:  pavelleonidov/module-tinymce4 2.0.0 requires php ~5.5.0|~5.6.0|~7.0.0|~7.1.0|~7.2.0 -> your PHP version (7.3.15) does not satisfy that requirement.

How can I fix that?

readiness check does not go through because of that error, when trying to update modules via magento's backend...

regards

**Comment by patricklewis** [comment]
@pavelleonidov Seeing a similar error with PHP 7.3.18:

```
$ composer require pavelleonidov/module-tinymce4


  [InvalidArgumentException]
  Package pavelleonidov/module-tinymce4 at version  has a PHP requirement incompatible with your PHP version (7.3.18)
```

**Comment by pavelleonidov** [comment]
Fixed with https://github.com/pavelleonidov/magento2-tinymce4/pull/16
