### ISSUE TITLE
Magento 2.4 support

### ISSUE THREAD

**Issue by WebKenth** [pavelleonidov/magento2-tinymce4#18]
https://github.com/pavelleonidov/magento2-tinymce4/blob/master/composer.json#L6

Magento 2.4 has updated Module-backend to 102

**Comment by pavelleonidov** [comment]
Hi,

thanks for reporting! I have extended the dependency constraints for module-backend and module-framework, so you should be able to install this module in a Magento 2.4 environment now. However, I have not yet tested against Magento 2.4, so if you face any problems, feel free to submit a new issue.

Best regards,

Pavel
