### ISSUE TITLE
i installed this module but not working

### ISSUE THREAD

**Issue by sumeetmobiwebtech** [pavelleonidov/magento2-tinymce4#2]
i installed this module but not working still getting error.
i am using magento 2.3

Still getting error in admin cms block -
1 - Failed to load resource: the server responded with a status of 404 (Not Found)
2 - require.js:141 Uncaught Error: Script error for: tinymce
http://requirejs.org/docs/errors.html#scripterror
at makeError (require.js:166)
at HTMLScriptElement.onScriptError (require.js:1681)

Please anyone there how guide me step by step

**Comment by pavelleonidov** [comment]
Hi Sumeet,

please check issue #3.

Best regards,

Pavel
