### ISSUE TITLE
Tinymce4 is compatibility for Magento2.3.1 CE? 

### ISSUE THREAD

**Issue by nagarajuk12** [pavelleonidov/magento2-tinymce4#3]
Hello Pavel Leonidov,

We have upgraded Magento 2.2.3 CE to 2.3.1 CE successfully. But we are facing few issues with the TinyMCE editor when production edit, cms pages, and blocks, etc.. Please let us know is this "pavelleonidov/magento2-tinymce4" module will help us to resolve & compatibility for Magento 2.3.1 CE ?

Please refer: https://magento.stackexchange.com/questions/276345/magento-2-3-1-ce-tinymce-error?noredirect=1#comment394022_276345

Please advise ASAP. 

Thanks

**Comment by pavelleonidov** [comment]
Hi KnK123,

originally, I had written this module for the versions 2.1 and 2.2 of Magento and there were no plans to maintain it for 2.3 since the core integration of TinyMCE 4 had been announced for 2.3. But I know about the issues with the core upgrade - so I had extended the dependency constraint of my module to 2.3 and it is used by a client of me without issues. So you can give it a try. Let me know if you experience issues and I will do my best to help you.

Best regards,

Pavel

**Comment by nagarajuk12** [comment]
Thanks for your support and quick reply Pavel.
Good News, this module has been fixed my above issue which I shared above.  I have tried and installed this module at app/code directory its working fine.

But I have found a few observations when I using on Magento 2.3.1 CE. I would like to share my observations it may help others who are willing to use this module. 

observations:

1. Unable to Insert Image & video using this module.
   [https://drive.google.com/file/d/1nDY-J-ayMWFxFBiwB3_BeM6yTZaBwQ0f/view](https://drive.google.com/file/d/1nDY-J-ayMWFxFBiwB3_BeM6yTZaBwQ0f/view)

2.  Unable to Insert widget on cms & block pages
  [https://drive.google.com/file/d/1omeAjpgOYBTYR0YHUWVAs0tkdW936aAD/view](https://drive.google.com/file/d/1omeAjpgOYBTYR0YHUWVAs0tkdW936aAD/view)
https://prnt.sc/nuu7bv

Thanks

**Comment by pavelleonidov** [comment]
Hi KnK123,

thank you very much for your detailed report! I will check it out and provide a solution for these issues ASAP, so stay tuned. :)

Best regards,

Pavel

**Comment by henrikschytte** [comment]
Hi is there a solution yet .. and where do i add more plugins to it

**Comment by pavelleonidov** [comment]
Hello guys,

after refactoring Magento 2.3's core implementation I have managed to fix the issues - it's working at production mode as well. For now, you can use the branch magento23-compatibility of this module - I will merge it to master later on. When using the composer method of your Magento 2 installation, make sure you take the proper version constraint:

`"pavelleonidov/module-tinymce4": "dev-magento23-compatibility"`

Also, if you're not using the system's default adapter in your configuration, make sure you select "Alternative TinyMCE 4" in Magento 2 backend: Stores -> General -> Content management -> WYSIWYG Editor.

@henrikschytte :

The TinyMCE 4 flavor of this module already contains several additional plugins and the menu bar. They are implemented inside the config provider - see:
https://github.com/pavelleonidov/magento2-tinymce4/blob/magento23-compatibility/Model/Config/Wysiwyg/Config.php

If you want to set up a different plugin config, you may override this file with the preference method. I will create a backend module to make a more simple way for customization possible when I have time.

**Comment by pavelleonidov** [comment]
The updates are now merged to master and tagged to 2.0.0, see also new README.md. If you experience any new issues, feel free to file a new issue.

Best regards,

Pavel
